ss220club/Paradise

code/modules/mob/living/simple_animal/friendly/mouse.dm
Возвращаем возможность крысам таскать еду с контейнерами, а также ножи и кухонные принадлежности, аля вилок и ложек.
Крысы по прежнему не могут больше таскать всякие мышелочки, капканы и прочие предметы которые ДЕЙСТВИТЕЛЬНО могли бы повлиять на геймплей где-то помимо кухни или испортить собственную поимку.
На крыс по прежнему действуют ограничения по размерам. Они не смогут таскать контейнеры, еду и кухонные принадлежности больше их по размеру.
То, что предназначалось для старого СС220 после авоутов, но я не успел туда создать ПР.
=> FEAT: Return rat pull kitchen items and food

_maps/map_files/cerestation/cerestation.dmm, _maps/map_files/cyberiad/cyberiad.dmm
Убирает лишние решётки у окон на шаттле Цере, т.к. спавнер окон шаттла сам спавнит их, при этом жалуясь на лишние решётки, удаляя их.
Убирает вторые окна в одном тайтле на шаттле Кибериады.
=> fix: runtime and double windows on shuttles

code/modules/clothing/spacesuits/hardsuit.dm
Починил отображение шлема механика со включенным светом
https://discord.com/channels/1097181193939730453/1101546912814989483
=> Fix: mechanic light-on helmet state

code/game/gamemodes/nuclear/lone.dm
Увеличивает минимальное число игроков для ивента.
Теперь есть анонс через 5 минут после начала ивента.
=> Tweak: solonuke nerf

code/game/mecha/paintkits.dm, code/modules/research/designs/mechfabricator_designs.dm
Удешевляет наклейки на мехов в цене, техах, скорости производства. 
-Все небоевые мехи "Кларк, Рипли, Огнеборец, Одиссей" получили порог технологий наклеек до 5 техов, чтобы они были доступны раундстартом, когда они собственно и делаются. 
-Стоимость наклеек для небоевых мехов снижена, чтобы можно было с первыми ресурсами их построить. Скорость производства снижена с овердохуя до 10-20 секунд. 
-Все наклейки, доступные рипли и огнеборцу, теперь доступны И рипли И огнеборцу, потому что это буквально один рескин другого..
-Наклейки остальных мехов получили удешевление по техам на 1, кроме синди гигакса, он все еще требует 3 нелегал. -Скорость производства стала фиксированной: 20 для гигакса, 30 для дюранда, 40 для фазона -Цена наклеек на боевые мехи практически не изменилась.
Обсуждено с …
=> FIX: Cheaper paintkits

code/modules/w_examine/descriptions/structures.dm
Добавлена [Справка] к фальшстенам, чтобы она не отличалась от обычных стен
Описание
Теперь у фальшстен есть такая же [Справка] как и у обычных стен.
Причина создания ПР:
Фикс ошибки из канала баг-репорты
(https://discord.com/channels/1097181193939730453/1102226047061196861)
=> false wall fix

code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
Устраняет проблему вызванную перезаписью контента шкафа химиков РнД ПРом
https://github.com/ss220club/Paradise/pull/122
Багрепорт
Стало
Было
=> Fix: Research closet rewrites contents

code/game/jobs/job/security.dm, code/game/objects/structures/crates_lockers/closets/secure/security.dm
Убирает раундстартовые кейсы с сибилами у Вардена и ГСБ, перемещает их им в ящики.
Отсутствие кейсов с сибилами, если нет кого-либо из вышеперечисленных на смене.
=> fix: Sibyl lockboxes

code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Багфиксит исчезновение Seed Storage.
Изменение icon_state позволит быстро и не запариваясь решить проблему с исчезающим спрайтом Seed Storage. Возникала эта проблема из-за того, что при добавлении семян в Seed Storage его icon_state из-за родительского smartfridge менялся с seeds на seeds1, seeds2 и seeds3 по мере увеличения кол-ва семян. Такая же проблема может возникнуть и в других дочерних от smartfridge машинах.
Ссылка на багрепорт: https://discord.com/channels/1097181193939730453/1112370458923372624/1112370458923372624
=> FIX: Seed Storage visual bug

code/game/mecha/equipment/tools/medical_tools.dm
фиксит невозможность снять модуль ног с синди шкафомеха.
=> FIX: Odyss leg upgrade

code/__DEFINES/is_helpers.dm, code/game/objects/items/weapons/grenades/chem_grenade.dm, code/modules/reagents/reagent_containers/glass_containers.dm, code/modules/research/designs/medical_designs.dm
Корректировки нового бикера.
- Подняты техи до 7-7-7 (было 7-7-6)
Корректировка старых бикеров.
- Маленькие теперь вмещают 60 юнитов вместо 50
- Большие вмещают 120 вместо 100
Корректировка гранат.
- Бикер на 1000 юнитов нельзя вставить в гранаты
- Так же нельзя делать голосовые гранаты (я запрещаю вам нюхать Jokerge)
Б - Баланс
https://github.com/ss220club/Paradise/assets/69762909/c5daf2e3-b0de-43e2-9b01-ed8a986d46d8
=> [PRIME] Beaker balance

code/modules/research/designs/medical_designs.dm
Поднятие цен на БС бикеры
Ещё одни балансные правки
=> [PRIME] Tweak: Bluespace beaker balance 2

_maps/map_files/cyberiad/cyberiad.dmm, code/game/machinery/doors/airlock_control.dm, code/game/machinery/embedded_controller/airlock_controllers.dm, code/game/turfs/simulated/walls_misc.dm
Забыл базовую иконку для ржавых стен + фикс icon_state дверей в ксено на коробке.
Так же фикс кнопок ПОД новыми окнами
=> Fix: Buttons under windows

SQL/paradise_schema.sql, SQL/updates/29-30.sql, code/__DEFINES/misc.dm, code/__DEFINES/preferences.dm, code/_onclick/hud/hud.dm, code/_onclick/hud/parallax.dm, code/game/gamemodes/miniantags/slaughter/slaughter.dm, code/game/objects/items/blueprints.dm, code/game/objects/items/devices/lightreplacer.dm, code/game/turfs/turf.dm, code/modules/client/client_defines.dm, code/modules/client/client_procs.dm, code/modules/client/preference/preferences.dm, code/modules/client/preference/preferences_mysql.dm, code/modules/client/view.dm, code/modules/mining/lavaland/loot/ashdragon_loot.dm, code/modules/mob/living/carbon/brain/MMI.dm, code/modules/mob/living/life.dm, code/modules/mob/mob.dm, code/modules/projectiles/firing.dm, code/modules/shuttle/navigation_computer.dm, code/modules/tgui/states/default.dm, code/modules/tooltip/tooltip.dm, code/modules/tooltip/tooltip.html, code/world.dm
Порт вайдскрина с оффов, https://github.com/ParadiseSS13/Paradise/pull/20861
<details>
<summary>Screenshots/Videos</summary>
</details>
=> feat: widescreen (https://github.com/ParadiseSS13/Paradise/pull/20861)

SQL/paradise_schema.sql, SQL/updates/30-31.sql, _maps/map_files/generic/CentComm.dmm, _maps/map_files/generic/z2_old.dmm, code/__DEFINES/flags.dm, code/__DEFINES/misc.dm, code/_onclick/hud/action_button.dm, code/_onclick/hud/alert.dm, code/_onclick/hud/blob_overmind.dm, code/_onclick/hud/ghost.dm, code/_onclick/hud/hud.dm, code/_onclick/hud/screen_objects.dm, code/_onclick/hud/screentip.dm, code/controllers/subsystem/titlescreen.dm, code/game/atoms.dm, code/game/objects/items.dm, code/game/turfs/simulated/floor.dm, code/game/turfs/simulated/walls_indestructible.dm, code/game/turfs/space/space.dm, code/modules/client/client_procs.dm, code/modules/client/preference/preferences.dm, code/modules/client/preference/preferences_mysql.dm, config/example/dbconfig.txt, interface/skin.dmf, paradise.dme
Порт screentips (текст по центру экрана, показывающий то, на что ты навелся) с https://github.com/ParadiseSS13/Paradise/pull/16505
Надо обновить БД
<details>
<summary>Screenshots/Videos</summary>
Стандарт
Выключен
Смена в префах
Обновленное окно (снизу-слева и цветовая гамма черного мода)
</details>
=> feat (port): Screentips

_maps/map_files/cyberiad/cyberiad.dmm, code/game/mecha/mech_fabricator.dm
Теперь можно самому решать в какую сторону с мех фаба будут выплёвываться детали.
По умолчанию выплёвываются вниз.
Добавил масла для ЕРП химикам меда и РнД
За помощь спасибо @Gaxeer 
Мехфаб выплёвывал в стену в новом робо...
Верьте на слово
=> Fix: Mech fab output direction

code/_onclick/click.dm, code/_onclick/other_mobs.dm, code/controllers/configuration.dm, code/datums/components/footstep.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/human/say.dm, code/modules/mob/living/carbon/human/species/_species.dm, code/modules/mob/living/carbon/human/species/abductor.dm, code/modules/mob/living/carbon/human/species/golem.dm, code/modules/mob/living/carbon/human/species/machine.dm, code/modules/mob/living/carbon/human/species/nucleation.dm, code/modules/mob/living/carbon/human/species/shadow.dm, code/modules/mob/living/carbon/human/species/skeleton.dm, code/modules/mob/living/carbon/human/species/vox.dm, code/modules/mob/living/carbon/human/species/wryn.dm, code/modules/mob/living/carbon/human/update_stat.dm, code/modules/mob/living/life.dm, code/modules/mob/living/living.dm, code/modules/mob/living/say.dm, code/modules/mob/living/update_status.dm, code/modules/mob/mob_helpers.dm, config/example/game_options.txt
Софткрит:
- Заменен хардкрит у хуманов на софткрит;
- Софткрит заставляет куклу лежать;
- Софткрит позволяет только шептать: нельзя пользовать рацией, говорить на расстоянии;
Ползание:
- Не позволяет использовать ЛКМ пустой рукой. Вообще. Исключение: наличие боевых искусств и антидроп (как и раньше).
- Даже нельзя собой двери открывать и стукаться об другие предметы.
- Ползание замедляет скорость на 4 децисекунды **И** заставляет "ходить", а не "бежать". Читай, скорость ползания - дважды ходьба.
- При ресте, теперь наоборот задержка перед движением, когда встали, а не когда упали.
В итоге:
- Можно ползать, но это не дает ничего, кроме как замедленного передвижения И возможности проползать под кем-то или определенными объектами. Ни кнопку не нажать, ни оружие не достать, даже обниматься …
=> SoftCrit Rework + Crawling

_maps/map_files/Delta/delta.dmm, code/game/machinery/alarm.dm, code/game/machinery/door_control.dm, code/game/machinery/firealarm.dm, code/game/machinery/lightswitch.dm, code/game/machinery/requests_console.dm, code/game/objects/items/devices/radio/intercom.dm, code/game/objects/structures/window.dm, code/modules/newscaster/obj/newscaster.dm, code/modules/power/apc.dm
Настенная машинерия больше не должна быть под окном.
Trust me
=> Fix: Wall machinery under windows

_maps/map_files/Delta/delta.dmm, _maps/map_files/cerestation/cerestation.dmm, _maps/map_files/cyberiad/cyberiad.dmm, code/datums/supplypacks.dm, code/modules/research/designs/autolathe_designs.dm
Убирает слаги из автолата и из карго. Следующий шаг - бакшоты Jokerge
=> [FEAT] Slugs are Gone

code/controllers/subsystem/jobs.dm, code/game/jobs/job/civilian.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/job.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm, code/game/jobs/job/supervisor.dm, code/game/jobs/job/support.dm, code/modules/economy/Accounts.dm
Пересчёт начальных бабок у кекипажа и аккаунтов. Начало попыток в экономику на станции pepeOld
🐀 ge
Find out ingame
=> feat: economy startup pepepizdez

code/datums/spells/conjure_item.dm, code/datums/spells/devil.dm, code/game/gamemodes/devil/devil_game_mode.dm, code/game/gamemodes/devil/devilinfo.dm, code/modules/projectiles/projectile/magic.dm
Do i brought bugs also?Let's see
Добавляет инфернальному фаеболу к огню еще малый взрыв
Джаунт вместо 15 секунд требует 10 для появления/исчезновения и можно выйти из любого места
~~Изменяет~~Ломает прогрессию дьяволам
По просьбе JustPaper для эксперементов
=> Small buff on devils and progressing experiment
