- code/game/objects/structures/false_walls.dm
Запрещает фальшстене закрываться, если внутри есть что-то, что мешает проходу (имеется `density`), что запретит прятать в стенах различные машинери (тесла коилы), структуры (культа) и всё остальное, что имеет `density`
Фальшстена довольно странная вещь, которая активно используется для сокрытия вещей в стенах: консолей (аплоуды), структур культа, тесла коилов и прочего, что не обнаружить без мезонов или активной метаигры.
[Ссылка на обсуждение, одобрено](https://discord.com/channels/1097181193939730453/1099614262403538984)
> feat: Falsewall can't close with dense objects inside

- code/controllers/subsystem/mapping.dm
Убирает Тайпан из спавнов. Генерацию "запрещенных зон Тайпана" не проверял.
https://discord.com/channels/1097181193939730453/1100126411664150649
> Del: Remove Taipan from spawning

- .github/workflows/ci.yml
- .github/workflows/label_merge_conflicts.yml
- .github/workflows/render_nanomaps.yml
- code/datums/revision.dm
> fix: Run CI, rename branches

- .github/workflows/label_merge_conflicts.yml
На самом деле это не фикс, Я ВАС ОБМАНУЛ Jokerge
Попытка скрыть красные крестики в пуш коммитах.
> Fix: Merge conflict detection

- code/modules/research/designs/biogenerator_designs.dm
Возвращение странных семян в биогенератор ботаников, с увеличением их цены до 10 000.
Семена были удалены ради нёрфа ботаники, увы это не помогло, а всё потому что они использовались в основном ради лудомании, разнообразия и фана спуста примерно час раунда.
[Ссылка](https://discord.com/channels/1097181193939730453/1100113991021363290) на обсуждение, одобрено.
> Feat: Return of strange seeds into the biogenerator.

- .vscode/extensions.json
> updated recommended extentions

- code/modules/text_to_speech/seeds/silero.dm
Описание: исправление категории голоса Lynette на женский
> Fix: change gender for "Lynette"

- code/modules/world_topic/status.dm
Добавляет айди раунда в запрос статуса
> Feat: round id in status topic

- README.md
Исправлена ссылка на Discord, а также на статистику репозитория
> docs: Исправлены ссылки в README

- .github/workflows/label_merge_conflicts.yml
> Fix: Incorrect event naming for merge conflict detection

- .github/workflows/label_merge_conflicts.yml
Заменяет Action на другой, который во-первых не должен падать при пуше, во-вторых имеет больше опций, в-третьих обновляется.
https://github.com/eps1lon/actions-label-merge-conflict
> Feat: New Merge Conflict Detection

- .github/workflows/label_merge_conflicts.yml
Даёт пермишен, раз такого нет у Github токена.
> Fix: Permissions for merge conflict action

- code/game/gamemodes/nuclear/lone.dm
- code/modules/events/event_container.dm
- paradise.dme
Добавляет новый ивент: оперативник-одиночка
> Feat: lonenuke

- code/modules/text_to_speech/seeds/silero.dm
Исправление
https://discord.com/channels/1097181193939730453/1100421475040776364
> Fix: Misstake in TTS category

- code/modules/client/client_procs.dm
Твик прайса у донатеров согласно подпискам на Бусти, чтобы Хосту проще было ориентироваться в БД.
Нужно одобрение Морти.
> Tweak: Donator budget

- code/game/objects/items/weapons/storage/boxes.dm
Когда менял иконки, случайно (или специально) удалил букву и забыл вернуть, из-за чего коробки с инжекторами пустуют.
Очередной раз обкакался
> Fix: Empty injector box

- code/game/machinery/vending.dm
MERGE NOW!
Добавляет костюм монке в АвтоДроб. То, что нужно билду. То, чего не хватало билду. Две строчки, изменившие мир.
Вокс-монке блеядь, что еще надо? 
Этот костюм нужен билду.
> MONKE SUIT

- code/modules/client/preference/preferences_mysql.dm
Исправление Рантайма
[Оригинал PR](https://github.com/ParadiseSS13/Paradise/pull/16464)
> Fix: Runtime caused by null client preferences

- code/modules/surgery/organs/subtypes/diona.dm
Фиксит рантайм при отсутствии майнда у дионы
> Fix: diona_brain_evacuation/IsAvailable runtime

- code/modules/shuttle/shuttle.dm
Оригинальный ПР: https://github.com/ParadiseSS13/Paradise/pull/18194
Полы шаттлов более не будут спавнить космос и другие нежелательные турфы, если разрушены. Что-угодно, что будет находится на разрушенном тайле пола, будет проигнорировано для транфсера. Помимо этого шаттлы подлежат восстановлению от нежелательных турфов.
> Refactor: Shuttles not take space/lava/chasms with them on transit

- code/controllers/configuration.dm
- code/modules/pixel_shift/pixel_shift.dm
- config/example/config.txt
Черри-пик для Прайм ветки, а то ломается с последним изменением
https://github.com/ss220club/Paradise/pull/28
> feat: Pixel-Shift (#28)

- code/modules/admin/admin_verbs.dm
Теперь разрабы смогут использовать деадмин.(Как и любые другие роли с выборочными правами без +админ\модер\ментор, как и должно быть, тк любые права, кроме рантаймов, дают кнопку деадмина)
> Fix: deadmin rights

- code/datums/datumvars.dm
- code/modules/admin/admin_verbs.dm
Теперь можно использовать vv не обладая админкой, но обладая R_VAREDIT
> Fix: devs vv

- _maps/map_files/cyberiad/cyberiad.dmm
Запрос изменений от Lear the cat:
появился автомат в углу с запчастями для крафта бомб, добавился столик с обычными белыми перчатками, добавился между рабочими местами холодос для складывания всей химии, появился 2й личный шкаф у химика
Стёкла из обычных укреплённых заменены на плазмостёкла укреплённые
в остальном тоже самое по ресурсам.
https://discord.com/channels/1097181193939730453/1101927353476726924
> Feat: RnD chemistry [BOUNTY]

- code/modules/text_to_speech/seeds/silero.dm
> Tweak: voices donate tiers

- code/modules/text_to_speech/seeds/silero.dm
> Mirror: Voice tiers

- _maps/map_files/Delta/delta.dmm
- _maps/map_files/cerestation/cerestation.dmm
- _maps/map_files/cyberiad/cyberiad.dmm
- code/game/objects/structures/decor/decor.dm
- code/modules/client/preference/preferences_spawnpoints.dm
- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/new_player/new_player.dm
Заменяет фразу появления персонажа с "прибыл на станцию" на "вышел из криосна". Добавляет декоративные криоподы на шаттлы прибытия на всех картах. Перемещает все спавн поинты киборгов на сателит, кроме дельты, где они остались в зарядниках робо.
https://discord.com/channels/1097181193939730453/1099657504750829688
> Awaking now!

- code/datums/datumvars.dm
Фиксит VV разрабам в меню рантаймов.
> Fix: dev VV in runtime menu

- code/modules/mob/living/simple_animal/hostile/alien.dm
Исправляет путь к иконке мертвой квины
> Fix: Alien queen dead sprite

- code/modules/mob/living/living.dm
- Убирает урон от пулла
- Замена стаминакрита на стан на 2 тика
[Ссылка на обсуждение](https://discord.com/channels/1097181193939730453/1101910575082119179)
> tweak: Remove damage from pulling

- _maps/map_files/cyberiad/cyberiad.dmm
Окна заменены на затемняющиеся.
Небольшая перестановка, в том числе труб.
Минорное обновление, приватные беседы с КМом и небольшая перестановка (в том числе труб).
Прошу залить сразу и на мейн и на прайм. Так как кибериада пока только на прайме.
[DIFF](https://mdb2.affectedarc07.co.uk/images/629123117/13122290233/m/0/0-diff.png)
До:
После:
> Feat: (Cyberiad) Polarized windows in QM office and a couple of improvements.

- _maps/map_files/cyberiad/cyberiad.dmm
Вся инфа тут - https://discord.com/channels/1097181193939730453/1097543419586428989/1100799038699356251
Повышение удобства, улучшение внешнего вида, наведение порядков.
[DIFF](https://mdb2.affectedarc07.co.uk/images/629123117/13120543284/m/0/0-diff.png)
Финальный вид карты -
> Feat: (Cyberiad) Medbay remap

- _maps/map_files/cyberiad/cyberiad.dmm
Стягивание всех изменений кибериады с мейна на праймс
> Feat: Cyberiad to prime

- _maps/map_files/cyberiad/cyberiad.dmm
> Revert "Feat: Cyberiad to prime"

- code/modules/mob/holder.dm
- code/modules/mob/living/simple_animal/friendly/cat.dm
Починил иконку удержания Бедокура
Временно невидим в руках, так как отсутствуют спрайты
https://discord.com/channels/1097181193939730453/1102594039934615592
> Fix: Bedokur holder icon

- code/game/mecha/combat/combat.dm
- code/game/mecha/combat/durand.dm
- code/game/mecha/combat/gygax.dm
- code/game/mecha/combat/honker.dm
- code/game/mecha/combat/marauder.dm
- code/game/mecha/combat/phazon.dm
- code/game/mecha/equipment/mecha_equipment.dm
- code/game/mecha/equipment/tools/medical_tools.dm
- code/game/mecha/equipment/tools/mining_tools.dm
- code/game/mecha/equipment/tools/other_tools.dm
- code/game/mecha/equipment/tools/work_tools.dm
- code/game/mecha/equipment/weapons/weapons.dm
- code/game/mecha/makeshift/lockermech.dm
- code/game/mecha/mecha.dm
- code/game/mecha/mecha_actions.dm
- code/game/mecha/mecha_topic.dm
- code/game/mecha/medical/odysseus.dm
- code/game/mecha/working/working.dm
Почти полная локализация интерфейса мехов, теперь даже самые недружественные к английскому люди смогут спокойно им управлять.
Добавлено включенное ТО Гигаксу, дюранду и Фазону наподобии их младших братьев, их продвинутые версии не затронуты по причине ненадобности.
Ровер, Темный Гигакс и Маулер при покупке появляются с слаймовой батареей и ремонтным дроидом, вместо Тесла Реле и блюспейс батареи, по причине того что они стоят 70-140 ТК,  за такую титаническую стоимость у них слишком низкая живучесть и слишком высокая энергозависимость.
https://discord.com/channels/1097181193939730453/1100384349217624166/1100384349217624166 альтернатива предложке, которая не трогая кучу кода по факту делает то же самое.
+
Множество обсуждений с АДРом и другими уважаемыми личностями
Да, "Шприцев" уже …
> Localization to mechs + buff syndie mechs

- _maps/map_files/cyberiad/cyberiad.dmm
Вернул потерянный штамп СМО. Немного подправил хирургию.
Докинул карантинных бластдоров.
Вернул болты психу.
Небольшая перестановочка и чистка мусора.
> Fix: (Cyberiad) New Medbay fixes.

- _maps/map_files/cyberiad/cyberiad.dmm
* fix
* lockdown
* door bolt for psych
* del ai monitor
* some fixes
* second surgery replacement
* one more
> Fix: [Prime] (Cyberiad) New Medbay fixes.

- code/modules/space_dragon/carp.dm
- code/modules/space_dragon/carp_rift.dm
- code/modules/space_dragon/mob.dm
- Убрана броня
- Добавлено ночное зрение дракону и карпам
- Убран урон по своим у дракона и карпов
- Исправлено имя у карпов
- Добавлено ХП карпам (25 -> 60)
> Feat: Space Dragon balance tweaks

- _maps/map_files/cyberiad/cyberiad.dmm
Зарядил дефибы, отдал химический худы химикам, добавил по 2 мед худа и пояса, убрал по 1 аптечке каждого типа.
Немного подвигал кривые объедки.
Починил дверь психа.
Работа над ошибками.
[DIFF](https://mdb2.affectedarc07.co.uk/images/629123117/13241335647/m/0/0-diff.png)
> Fix: (Cyberiad) Another fixes for new Medbay

- code/modules/space_dragon/mob.dm
fix: space dragon revivable with lazarus
> fix: space dragon revivable with lazarus

- code/game/gamemodes/miniantags/guardian/types/healer.dm
Убирает проблему того, что голопара-целитель не лечил.
> FIX: Holo heal

- _maps/map_files/cyberiad/cyberiad.dmm
Добавляет бригмеду его риг.
Возвращает генетикам шкаф и бикер с криоксадоном в клонёрку.
У него есть риг но его нет на коробке.
> Feat: (Cyberiad) Brigmed Hardsuit and genetics closet back

- code/modules/text_to_speech/seeds/silero.dm
> Added new TTS voices

- code/modules/space_dragon/carp_rift.dm
Уменьшает интервал между карпами вдвое
Баффаем дракончика
> tweak: Buff to carp rift

- _maps/map_files/cyberiad/cyberiad.dmm
Reverts ss220club/Paradise#108
> Revert "Feat: [Bounty] (Cyberiad) ERP corner..."

- code/modules/research/xenobiology/xenobiology.dm
усиливает физдамаг и лазер зелья в 2 раза.
https://discord.com/channels/1097181193939730453/1110572747853135965
> BOUNTY: Xeno potions buff

- code/modules/client/preference/loadout/loadout_donor.dm
> fix: donator loadout

- _maps/map_files/cyberiad/cyberiad.dmm
Вернул пропавшую консоль криокапсулы синтов в робо.
Перенесите пожалуйста заодно и на прайм Jokerge
> fix: Missing console

- code/controllers/subsystem/discord.dm
- code/controllers/subsystem/ticker.dm
- code/modules/client/client_procs.dm
> Remove: ping for some admin msgs

- _maps/map_files/cyberiad/cyberiad.dmm
Добавил ангар механику и ЕВУ
Добавлен небольшой ангар для подов механику, перемещены ворота, добавлена ЕВА для исследователей космоса почти как на дельте.
Личное баунти, одобрено Мунивёрсом.
> [PRIME] Hangar mechanics

- _maps/map_files/cyberiad/cyberiad.dmm
Выдан доступ эксплорерам к механику, больше не надо просить доступ у ГП шоб припарковать под
Ангар есть, доступа нет
[DIFF, зачем если в коде видно...](https://camo.githubusercontent.com/91dac21878707c0bd16e673d31fc284f2bda1644475c669c11771a86c3197e12/68747470733a2f2f6d6462322e616666656374656461726330372e636f2e756b2f696d616765732f3632393132333131372f31343333383638313134342f6d2f302f302d646966662e706e67)
> Access to mechanic for keksplorers

- _maps/map_files/cyberiad/cyberiad.dmm
Синхронизация коробки с мейновской (более свежей по всей видимости)
Заебали конфликты, идём на радикальные меры
> [PRIME] Fix: Test sync Cyberiad

- _maps/map_files/cyberiad/cyberiad.dmm
У механика оказывается антажные перчатки инженеров, за 8 ТК
Кто-то обосрался, кто-то не усмотрел
> Fix: Bad insulating gloves at the mechanic

- _maps/map_files/Delta/delta.dmm
Я ненавижу того кто расставлял настенную машинерию на дельте...
Новые срайты
> Fix: Delta machinery directions

- _maps/map_files/generic/CentComm.dmm
> Fix: SCC hole

- _maps/map_files/cyberiad/cyberiad.dmm
Ремап робо и стойки РнД.
Больше удобства, больше порядка, больше красоты и дополнительный протолат с принтером плат.
Заказ Лира и собственное желание
> Feat: RnD and Robotics remap

- code/__DEFINES/colors.dm
- code/modules/client/client_procs.dm
- code/modules/input/input.dm
Даркмод теперь меняет цвет нижней-правой панели
Поле ввода теперь всегда в "даркмоде"
<details>
<summary>Screenshots/Videos</summary>
</details>
> Better darkmode

- code/controllers/configuration.dm
- code/game/machinery/computer/robot.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/mob/living/silicon/silicon.dm
- config/example/config.txt
- Добавляет через конфиг блокировку режима мультисенсора у боргов (по умолчанию выключена)
- Добавляет `Reset Identity Codes` в `Robot Commands` емагнутым боргам, которая снимает локдаун и стирает их с БД станции (консоли, ИИ)
- Взрыв емагнутого борга активирует `Reset Identity Codes` и деактивирует взрыв
- Апдейт экзмпл конфига
Включить в конфиге `MULTISENSOR_BORGS_DISABLED`
trust me bro
> feat: Borgs changes

- code/game/objects/items/weapons/AI_modules.dm
- code/modules/research/designs/AI_module_designs.dm
- code/modules/research/designs/comp_board_designs.dm
- Платы ИИ без кейса
- Загрузка законов повышена с 20 до 30 секунд
trust me bro
> prime changes

- _maps/map_files/cyberiad/cyberiad.dmm
Устраняет утечку плазмы в токсинах (наверное)
Заменяет обычные окна на спавнеры
Фикс пары недочётов
> Fix: Plasma leak and bad windows

- code/game/machinery/firealarm.dm
Изменение иконки файралярмы при ручном триггере
> fix?: firealarm icon change on activateion

- code/controllers/subsystem/ticker.dm
Убирает смену тайтла при завершении загрузки (остаток от того, что был тайтл отдельный под загрузочный экран)
> fix: Removed backdoor for loading-loaded title screen

- _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
Раздробил два огромных астероида, на более естественные скопления.
> Tweak: Little USSP inprovements

- code/datums/ruins/space.dm
- paradise.dme
Запрещает спавниться космической руине "USSP_gorky17_collapsed"
Initializations complete within 210.6 seconds!
> Del: USSP_gorky17_collapsed

- _maps/map_files/Delta/delta.dmm
- _maps/map_files/cyberiad/cyberiad.dmm
Удалены боевые перчатки с оружейки на Кибериаде и Керберосе (снова)
> Remove: Combat gloves from armory

- code/modules/projectiles/guns/syringe_gun.dm
Блюспейс шприц теперь можно достать
Но если шприц последний, его достать нельзя
Увы
> fix: Syringegun fix?

- _maps/map_files/generic/CentComm.dmm
Добавил кнопочки в тюрьму на ЦК
Почистил пару параш
Поменял пару окон
Поправил пару неровностей
> Little CentCom cleaning

- _maps/map_files/cyberiad/cyberiad.dmm
Добавил ботанический раздатчик и очки в гидропонику.
Вай нот? На дельте это давно сделано, минусов нет, только плюс в виде меньшей нагрузки на РнД, которое и так молча приносит раздатчик чуть ли не раундстартом.
Trust me
> Tweak: Botany dispenser and glasses (Cyberiad)

- _maps/map_files/cyberiad/cyberiad.dmm
Кто-то дал ХоСу в руки плётку...
Oh yes sir!
> Tweak: Chain of command for HoS (Cyberiad)

- _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
- code/modules/mob/language.dm
- code/modules/ruins/ussp_base.dm
Изменение названий, доступов, одежды у гостролей Космической Станции 13. 
Причина проста - Нынешнее состояние этой гостроли заставляет желать лучшего.
> Full redo of USSP ghostrole

- code/modules/mob/living/carbon/human/examine.dm
Добавляет сообщение при осмотре, что цель в крите
"Ты там точно в крите?"
> Crit Message

- _maps/map_files/Delta/delta.dmm
- _maps/map_files/cyberiad/cyberiad.dmm
Удаляет культистский точильный камень с Дельты и Кибериады.
Trust me брооу
> Del: Cult whetstone from maps

- _maps/map_files/cyberiad/cyberiad.dmm
Placed terminals on Cyberiad map for new economics update.
Дублирование пр-а на мастер ветку
> Map update: Cyberiad: EFTPOS placement.

- code/game/jobs/job/civilian.dm
> feat: make ASSistant rich again

- code/game/jobs/job/support_chaplain.dm
Gives poor chaplain not 0 money clueless
🌵 
🌵
> fix: give start money to chaplain xdd

- code/game/jobs/job/support_chaplain.dm
> fix: fix compilation error :ratge:
